### ISSUE TITLE
Socket Programming for PC

### ISSUE THREAD

**Issue by ruchitnaik** [cu-ecen-aeld/final-project-ruchitnaik#4]
### Socket Programming for PC

**DoD**
- [x] Basic Socket application on PC which sends and receives strings.

**Tasks**
- [x] Formulate the client code for socket communication.
- [x] Develop test code for local test of socket communication.
- [x] Test the socket communication between application code and test code.

**Blockers**
- [ ] Formulate logic to take user input to send strings

**Comment by ruchitnaik** [comment]
### Task 1
Developed client application code to communicate with the user entered IP. The code connects to specific IP of the server discoverable on the same socket port.
Application code: [Code](https://github.com/cu-ecen-aeld/final-project-ruchitnaik/blob/master/client_application/client.c)
Commit link: [commit](https://github.com/cu-ecen-aeld/final-project-ruchitnaik/commit/310b00752f36ad4b21728b5c51f293a34b860342)

**Comment by ruchitnaik** [comment]
### Task 2

Developed test code for the server application to accept the connection from the client on the specific socket port (3457 i.e same as that for client.
Test Code: [commit](https://github.com/cu-ecen-aeld/final-project-ruchitnaik/blob/master/client_application/server-test/server-test.c)
Commit link: [commit](https://github.com/cu-ecen-aeld/final-project-ruchitnaik/commit/fdb486cc7261c444457341dfda13e2cc8bd4683b)

**Comment by ruchitnaik** [comment]
### Task 3

- The test routine expects connection form client when test server is ready to accept connections.
![test-server_failure](https://user-images.githubusercontent.com/89817834/162663880-6a1f947b-0894-4ea8-8435-cac608753bf4.png)

- The connection from the client can be established by running the executable with server's IP as an argument. In this case, the server IP is 192.168.0.3. It was check form the below mentioned routine.
![ifconfig_with_IP](https://user-images.githubusercontent.com/89817834/162663784-d1f82d25-4780-4a5d-ad75-c95ce3a2d83c.png)
- Passing the IP as an argument to client executable establishes the socket connection.
- On connection establishment, the server would send a string and client would receive it and echo it on the terminal. On successful reception, client would send an acknowledgement string which the server would receive to print on the terminal. The server sends the string after 2 secs of receiving the response from client.

![client-test_success](https://user-images.githubusercontent.com/89817834/162664974-bd7c0dfc-f070-4979-b356-4aefcce6d3cb.png)
