### ISSUE TITLE
I2C sensor integration

### ISSUE THREAD

**Issue by ruchitnaik** [cu-ecen-aeld/final-project-ruchitnaik#5]
### I2C sensor integration

**DoD**
- [x] Implementing code to get temperature readings from the sensor

**Tasks**
- [x] Interface and detect the sensor
- [x] Code to get temperature readings from the sensor
- [x] Display the temp. readings on the terminal.

**Blockers**

- [x] [ Unable to check I2C functionality due SSH access issue](https://github.com/cu-ecen-aeld/final-project-ruchitnaik/issues/2).

**Comment by ruchitnaik** [comment]
Closing the issue.  
The issue is moved to another repository linked [here](https://github.com/cu-ecen-aeld/final-project-DivyeshShashikant/issues/2) and [here](https://github.com/cu-ecen-aeld/final-project-DivyeshShashikant/issues/3).
