### ISSUE TITLE
Create device tree patch for I2C dev

### ISSUE THREAD

**Issue by ruchitnaik** [cu-ecen-aeld/final-project-ruchitnaik#6]
### DoD

- [x] Create the I2C device patch and detect I2C1 and I2C2 device in /dev

### Tasks

- [x] Make necessary changes in .dtsi file related to I2C.
- [x] Create the patch file.
- [x] Generate the custom image with I2C patch.

### Blockers
No Blockers identified

**Comment by ruchitnaik** [comment]
### Task 1
Made Changes related to I2C-1 and I2C-2 device in the device tree file. It includes the pin configuration and adding the module in the device tree.

**Comment by ruchitnaik** [comment]
### Task 2
Generated the patch file successfully for i2C.
[Link](https://github.com/cu-ecen-aeld/final-project-ruchitnaik/blob/master/base_external/patches/linux/0001-creating-patch.patch)

**Comment by ruchitnaik** [comment]
### Task 3
Custom image hence generated loads both the I2C devices successfully.
Below is the screenshot with the image without I2C patch.
![before_patch_i2cdev](https://user-images.githubusercontent.com/89817834/162672209-4f0b6859-e06c-4ec5-afab-70cee405ee61.png)
After adding I2C patch to the image, all 3 I2C devices are successfully visible.
![I2C-dev-after-patch](https://user-images.githubusercontent.com/89817834/162672434-f66353eb-5220-4349-a1d0-363efb17282f.png)
