### ISSUE TITLE
Handling user input from terminal

### ISSUE THREAD

**Issue by ruchitnaik** [cu-ecen-aeld/final-project-ruchitnaik#7]
### DoD

- [x] Initialize 'socket send' command when-ever specific command is entered on terminal

### Tasks

- [x] Implementing shell script to take user input arguments
- [x] Re-direct these command to client application code.
- [x] Parse the received commands to execute 'socket send' on client application code.

### Blockers

- [x] Conceptualize the logic to implement shell script and direct it to the application code.

**Comment by ruchitnaik** [comment]
**Update 1**
Script conceptualized to manage netcat command to connect to the given port and enter the forever loop to send and receive commands. 
commit [link](https://github.com/cu-ecen-aeld/final-project-ruchitnaik/commit/1105f0fb6b2f51812642ccb15d97fe6137b868a5)

**Comment by ruchitnaik** [comment]
**Update 2**
The previous script implementation anyways runs in the blocking mode, hence does solve the purpose to implement it in the background to be non-blocking.
The implementation is integrated with the client application code to detect STDIO in the blocking mode to send command on the socket. 

commit [link](https://github.com/cu-ecen-aeld/final-project-ruchitnaik/commit/c5bd67470bfd7408256770c0c083a14d6e54306b)

![command_client](https://user-images.githubusercontent.com/89817834/163745672-a3cfb7a3-3603-44db-bdd7-309ced245087.png)
