### ISSUE TITLE
Socket Integration

### ISSUE THREAD

**Issue by ruchitnaik** [cu-ecen-aeld/final-project-ruchitnaik#8]
### DoD

- [x] Establish communication with the BBB over socket and send commands

### Tasks

- [x] Connect to BBB socket device
- [x] Send Command over TCP socket
- [x] Receive Data over TCP socket

### Blockers

- [x] Implementation of BBB's [server application](https://github.com/cu-ecen-aeld/final-project-DivyeshShashikant/issues/4)

**Comment by ruchitnaik** [comment]
**Update 1**
Server package added to the buildroot image for BeagleBone Black to test the server client communication where server is BBB and client is Linux based PC.
![image](https://user-images.githubusercontent.com/89817834/163746363-440d7c5b-cb7c-408a-a510-89fa07e8fb72.png)

**Comment by ruchitnaik** [comment]
**Update 2**

- The server implementation is successfully tested on Beaglebone black. The client application code interacts with the BBB socket port successfully.
- Client is able to send command on TCP socket to the BBB.
![image](https://user-images.githubusercontent.com/89817834/163747730-d1d5aef5-6e3f-4ece-92ac-6159daa8fd42.png)

**Comment by ruchitnaik** [comment]
**Update 3**

- Client receives the sensor data with appropriate readings and it's units. 
- The commands are implemented to receive temperature in degC and degF.
   - ```READC``` command returns the degC readings
     ![image](https://user-images.githubusercontent.com/89817834/163749535-5c84d488-aaff-4ed1-b410-a13cc067e68c.png)
   - ```READF``` command returns the degF readings. 
     ![image](https://user-images.githubusercontent.com/89817834/163749353-b9459e43-737a-43cd-a2d1-9574aac40551.png)
   - Any other command is responded with ```Enter valid command``` string. 
     ![image](https://user-images.githubusercontent.com/89817834/163749764-09d15b64-7d5c-4bc0-9f1d-354cc6813a64.png)

**Comment by ruchitnaik** [comment]
The server and client communication works as per the project overview definition.

- The client sends appropriate command and receive desired temperature readings.
   ![Client_Integrate_BBB](https://user-images.githubusercontent.com/89817834/163750270-a83a6d88-31fc-454c-8bb4-639d831c815d.png)

- The server receives and parses command and sends temperature data in appropriate format
   ![Server_Int_BBB](https://user-images.githubusercontent.com/89817834/163750421-5444c42d-dc86-4111-bbcd-37448120aee4.png)

Closing the issue with this comment
